/** Child invite intro — Figma 12914:11767 */
export const SIGNUP_CHILD_INVITE_INTRO_TOP_PX = 110;
export const SIGNUP_CHILD_INVITE_INTRO_W_PX = 327;
export const SIGNUP_CHILD_INVITE_INTRO_COLUMN_GAP_PX = 55;
export const SIGNUP_CHILD_INVITE_HERO_BLOCK_W_PX = 332;
export const SIGNUP_CHILD_INVITE_HERO_PX = 200;
export const SIGNUP_CHILD_INVITE_HERO_FADE_W_PX = 31;
export const SIGNUP_CHILD_INVITE_HERO_FADE_H_PX = 134;
export const SIGNUP_CHILD_INVITE_HERO_FADE_TOP_PX = 66;
export const SIGNUP_CHILD_INVITE_ALERT_BOX_RADIUS_PX = 15;
export const SIGNUP_CHILD_INVITE_ALERT_INNER_GAP_PX = 12;
export const SIGNUP_CHILD_INVITE_ALERT_PAD_X_PX = 19;
export const SIGNUP_CHILD_INVITE_ALERT_PAD_Y_PX = 16;
export const SIGNUP_CHILD_INVITE_ALERT_TEXT_W_PX = 294;
export const SIGNUP_CHILD_INVITE_INTRO_BUTTONS_GAP_PX = 12;
export const SIGNUP_CHILD_INVITE_INTRO_ACTIONS_PT_PX = 20;
export const SIGNUP_CHILD_INVITE_INTRO_ACTIONS_GAP_PX = 15;

/** Child invite share — Figma 12703:42221 (centered column) */
export const SIGNUP_CHILD_INVITE_SHARE_W_PX = 327;
export const SIGNUP_CHILD_INVITE_SHARE_OUTER_GAP_PX = 20;
export const SIGNUP_CHILD_INVITE_SHARE_INNER_GAP_PX = 29;
export const SIGNUP_CHILD_INVITE_BUTTONS_GAP_PX = 15;
export const SIGNUP_CHILD_INVITE_FOOTNOTE_MAX_W_PX = 297;

/** Child invite waiting — Screen 29 */
export type SignupChildInviteWaitingVariant = 'linkOpen' | 'companionPick';

export const SIGNUP_CHILD_INVITE_WAITING_LINK_OPEN_MS = 20_000;

export const SIGNUP_CHILD_INVITE_WAITING_CONTENT_TOP_PX = 284;
export const SIGNUP_CHILD_INVITE_WAITING_TEXT_W_PX = 332;
/** Figma 13035:2502 → 13035:2506 spacing */
export const SIGNUP_CHILD_INVITE_WAITING_TEXT_GIF_GAP_PX = 10;
export const SIGNUP_CHILD_INVITE_WAITING_LOGO_PX = 86.506;
/** Frame 1597882424 — bottom offset from screen edge */
export const SIGNUP_CHILD_INVITE_WAITING_MARQUEE_BOTTOM_PX = 110;
/** Wordmark tile — Figma 458×134 shell, 375×134 SVG @ 5% white */
export const SIGNUP_CHILD_INVITE_WAITING_MARQUEE_WORDMARK_W_PX = 458;
export const SIGNUP_CHILD_INVITE_WAITING_MARQUEE_WORDMARK_H_PX = 134;
export const SIGNUP_CHILD_INVITE_WAITING_MARQUEE_SVG_W_PX = 375;
export const SIGNUP_CHILD_INVITE_WAITING_MARQUEE_SVG_H_PX = 134;
/** Full path bounds — avoids cropping left “j” and right “e” tail */
export const SIGNUP_CHILD_INVITE_WAITING_MARQUEE_SVG_VIEWBOX = '-73 0 456 134';
export const SIGNUP_CHILD_INVITE_WAITING_MARQUEE_GAP_PX = 48;
/** Duplicated halves must match for seamless -50% loop */
export const SIGNUP_CHILD_INVITE_WAITING_MARQUEE_TILES_PER_HALF = 4;
export const SIGNUP_CHILD_INVITE_WAITING_MARQUEE_CYCLE_S = 20;
