/** Child invite intro — Figma 12914:11767 */
export const SIGNUP_CHILD_INVITE_INTRO_TOP_PX = 110;
export const SIGNUP_CHILD_INVITE_INTRO_COLUMN_GAP_PX = 55;
export const SIGNUP_CHILD_INVITE_HERO_PX = 200;
export const SIGNUP_CHILD_INVITE_ALERT_BOX_RADIUS_PX = 15;
export const SIGNUP_CHILD_INVITE_INTRO_BUTTONS_GAP_PX = 12;

/** Child invite share — Figma 12703:42221 */
export const SIGNUP_CHILD_INVITE_SHARE_TOP_PX = 196;
export const SIGNUP_CHILD_INVITE_CONTENT_W_PX = 332;
export const SIGNUP_CHILD_INVITE_OUTER_GAP_PX = 20;
export const SIGNUP_CHILD_INVITE_SECTION_GAP_PX = 29;
export const SIGNUP_CHILD_INVITE_BUTTONS_GAP_PX = 15;
export const SIGNUP_CHILD_INVITE_FOOTNOTE_MAX_W_PX = 297;
export const SIGNUP_CHILD_INVITE_REMIND_H_PX = 48;
export const SIGNUP_CHILD_INVITE_REMIND_BOTTOM_PT_PX = 20;
export const SIGNUP_CHILD_INVITE_HOME_INDICATOR_H_PX = 32;
